server:
  port: 8658
spring:
  rabbitmq:
    host: 217.182.73.245
  cloud:
    stream:
      bindings:
        input:
          destination: eventsourced-users
          group: noname
logging:
  level:
    org.springframework.cloud.stream: TRACE
